# Generated by Django 5.1.3 on 2025-10-30 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1SMR', '1º SMR'), ('2SMR', '2º SMR'), ('1ASIR', '1º ASIR'), ('2ASIR', '2º ASIR')], max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('nif_responsable', models.CharField(blank=True, max_length=16)),
                ('nombre_responsable', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('verde', 'Colabora'), ('naranja', 'En contacto'), ('rojo', 'No colabora')], default='verde', max_length=10)),
                ('filtro_ldap_alumnos', models.CharField(blank=True, help_text='Filtro LDAP opcional (ej: (o=%(cif)s)) donde se formateará con los campos de la empresa.', max_length=255)),
                ('cursos', models.ManyToManyField(blank=True, related_name='empresas', to='empresas.curso')),
            ],
            options={
                'ordering': ['-estado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_empresas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_persona', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Persona de contacto',
                'verbose_name_plural': 'Personas de contacto',
            },
        ),
    ]
