# Generated by Django 5.1.3 on 2025-10-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='filtro_ldap_alumnos',
        ),
    ]
