# Generated by Django 5.1.3 on 2025-10-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_empresa_filtro_ldap_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('curso', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='empresas.empresa')),
            ],
        ),
    ]
