# Generated by Django 5.1.3 on 2025-10-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alumnoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personacontacto',
            options={},
        ),
        migrations.AlterField(
            model_name='personacontacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='personacontacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personacontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
