# Generated by Django 5.1.3 on 2025-10-31 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_personacontacto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_username', models.CharField(max_length=150)),
                ('profesor_nombre', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contactos', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
