# Generated by Django 5.1.3 on 2025-11-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_historialcontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazas', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazas_curso', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Plaza por curso',
                'verbose_name_plural': 'Plazas por curso',
                'unique_together': {('empresa', 'curso')},
            },
        ),
    ]
