# Generated by Django 5.1.3 on 2025-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_plazacurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
