# Generated by Django 5.1.3 on 2025-11-01 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_empresa_cif'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_username', models.CharField(max_length=150)),
                ('profesor_nombre', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_alumno', to='empresas.alumnoempresa')),
            ],
            options={
                'verbose_name': 'Seguimiento de alumno',
                'verbose_name_plural': 'Seguimiento de alumnos',
                'ordering': ['-fecha'],
            },
        ),
    ]
