# Generated by Django 5.1.3 on 2025-11-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_historialalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoempresa',
            name='estado',
            field=models.CharField(choices=[('PROCESO', 'En proceso'), ('ASIGNADO', 'Asignado')], default='PROCESO', max_length=10),
        ),
    ]
