# Generated by Django 5.1.3 on 2025-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alumnoempresa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoempresa',
            name='estado',
            field=models.CharField(blank=True, choices=[('PROCESO', 'En proceso'), ('ASIGNADO', 'Asignado')], default=None, max_length=10, null=True),
        ),
    ]
