# Generated by Django 5.1.3 on 2025-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_alumnoempresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='profesor_responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
